# Generated by Django 5.1.1 on 2024-09-06 14:42

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('cupo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Dependencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_largo', models.CharField(max_length=100)),
                ('nombre_corto', models.CharField(max_length=10)),
                ('cupo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TallesRemeras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designacion', models.CharField(max_length=5)),
                ('alto', models.FloatField()),
                ('ancho', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=150)),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
                ('orador', models.CharField(max_length=100)),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AulaActividad', to='core.aula')),
            ],
        ),
        migrations.CreateModel(
            name='UserAsistente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.IntegerField(unique=True)),
                ('cuit', models.IntegerField()),
                ('fecha_nacimiento', models.DateField()),
                ('telefono_personal', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('telefono_emergencia', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('caracter', models.CharField(choices=[('asistente', 'Asistente'), ('coordinador', 'Coordinador'), ('chofer', 'Chofer')], default='asistente', max_length=15)),
                ('grupo_sangineo', models.CharField(choices=[('a+', 'A (+)'), ('b+', 'B (+)'), ('ab+', 'AB (+)'), ('o+', 'O (+)'), ('a-', 'A (-)'), ('b-', 'B (-)'), ('ab-', 'AB (-)'), ('o-', 'O (-)')], max_length=4)),
                ('regimen_comida', models.CharField(choices=[('ninguno', 'Sin Restricciones'), ('vegetariano', 'Vegetariano'), ('celiaco', 'Celiaco'), ('vegano', 'Vegano'), ('otros', 'Otros')], max_length=15)),
                ('regimen_comida_otro', models.TextField(blank=True, null=True)),
                ('alergia', models.CharField(choices=[('si', 'Si'), ('no', 'No')], max_length=2)),
                ('alergia_otro', models.TextField(blank=True, null=True)),
                ('medicamento', models.CharField(choices=[('si', 'Si'), ('no', 'No')], max_length=2)),
                ('medicamento_otro', models.TextField(blank=True, null=True)),
                ('dependencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.dependencia')),
                ('talle_ropa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tallesremeras')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asistente',
                'verbose_name_plural': 'Asistentes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserCoordinador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.IntegerField(unique=True)),
                ('cuit', models.IntegerField()),
                ('fecha_nacimiento', models.DateField()),
                ('telefono_personal', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('telefono_emergencia', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('caracter', models.CharField(choices=[('asistente', 'Asistente'), ('coordinador', 'Coordinador'), ('chofer', 'Chofer')], default='asistente', max_length=15)),
                ('grupo_sangineo', models.CharField(choices=[('a+', 'A (+)'), ('b+', 'B (+)'), ('ab+', 'AB (+)'), ('o+', 'O (+)'), ('a-', 'A (-)'), ('b-', 'B (-)'), ('ab-', 'AB (-)'), ('o-', 'O (-)')], max_length=4)),
                ('regimen_comida', models.CharField(choices=[('ninguno', 'Sin Restricciones'), ('vegetariano', 'Vegetariano'), ('celiaco', 'Celiaco'), ('vegano', 'Vegano'), ('otros', 'Otros')], max_length=15)),
                ('regimen_comida_otro', models.TextField(blank=True, null=True)),
                ('alergia', models.CharField(choices=[('si', 'Si'), ('no', 'No')], max_length=2)),
                ('alergia_otro', models.TextField(blank=True, null=True)),
                ('medicamento', models.CharField(choices=[('si', 'Si'), ('no', 'No')], max_length=2)),
                ('medicamento_otro', models.TextField(blank=True, null=True)),
                ('dependencia', models.ManyToManyField(to='core.dependencia')),
                ('talle_ropa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tallesremeras')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Coordinador',
                'verbose_name_plural': 'Coordinadores',
                'managed': True,
            },
        ),
    ]
