# Generated by Django 5.1.1 on 2024-09-15 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='hora_final',
            field=models.TimeField(default='00:00'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='hora_inicio',
            field=models.TimeField(default='00:00'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='portada',
            field=models.ImageField(default='#', upload_to=''),
        ),
    ]
