# Generated by Django 5.1.1 on 2024-09-04 20:34

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.IntegerField(unique=True)),
                ('cuit', models.IntegerField()),
                ('fecha_nacimiento', models.DateField()),
                ('telefono_personal', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('telefono_emergencia', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('caracter', models.CharField(choices=[('asistente', 'Asistente'), ('coordinador', 'Coordinador'), ('chofer', 'Chofer')], max_length=15)),
                ('grupo_sangineo', models.CharField(choices=[('a+', 'A (+)'), ('b+', 'B (+)'), ('ab+', 'AB (+)'), ('o+', 'O (+)'), ('a-', 'A (-)'), ('b-', 'B (-)'), ('ab-', 'AB (-)'), ('o-', 'O (-)')], max_length=4)),
                ('regimen_comida', models.CharField(choices=[('ninguno', 'Sin Restricciones'), ('vegetariano', 'Vegetariano'), ('celiaco', 'Celiaco'), ('vegano', 'Vegano'), ('otros', 'Otros')], max_length=15)),
                ('regimen_comida_otro', models.TextField(blank=True, null=True)),
                ('alergia', models.CharField(choices=[('si', 'Si'), ('no', 'No')], max_length=2)),
                ('alergia_otro', models.TextField(blank=True, null=True)),
                ('medicamento', models.CharField(choices=[('si', 'Si'), ('no', 'No')], max_length=2)),
                ('medicamento_otro', models.TextField(blank=True, null=True)),
                ('dependencia', models.ManyToManyField(related_name='dependencia', to='core.dependencia')),
                ('talle_ropa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talle_remera', to='core.tallesremeras')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='UserUsuario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Referente',
        ),
    ]
