# Generated by Django 5.1.1 on 2024-09-16 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_actividad_hora_final_actividad_hora_inicio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userasistente',
            name='cuit',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='usercoordinador',
            name='cuit',
            field=models.PositiveBigIntegerField(),
        ),
    ]
