# Generated by Django 5.1.1 on 2024-09-17 02:44

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_userasistente_cuit_alter_usercoordinador_cuit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='portada',
            field=models.ImageField(default='#', upload_to=core.models.generar_ruta_unica),
        ),
    ]
