# Generated by Django 5.1.1 on 2024-09-17 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_actividad_portada'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='asistente',
            field=models.ManyToManyField(blank=True, to='core.userasistente'),
        ),
    ]
