# Generated by Django 5.1.1 on 2024-09-17 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_actividad_asistente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actividad',
            old_name='asistente',
            new_name='asistentes',
        ),
        migrations.AlterField(
            model_name='aula',
            name='cupo',
            field=models.IntegerField(default=0),
        ),
    ]
