# Generated by Django 5.1.1 on 2024-09-17 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_asistente_actividad_asistentes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aula',
            name='nombre',
            field=models.CharField(max_length=30),
        ),
    ]
