# Generated by Django 5.1.1 on 2024-09-17 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_aula_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='habilitada',
            field=models.BooleanField(default=True),
        ),
    ]
