# Generated by Django 5.1.1 on 2024-09-18 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_actividad_inscripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='fecha',
            field=models.DateField(default='2024-9-18'),
        ),
    ]
