# Generated by Django 5.1.1 on 2024-09-25 16:54

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_actividad_fecha'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('logo', models.ImageField(upload_to=core.models.generar_ruta_unica_sponsor)),
            ],
        ),
    ]
